[workspace]
members = [
  "crates/yan-source",
  "crates/yan-syntax",
  "crates/yan-hir",
  "crates/yan-typeck",
  "crates/yan-mir",
  "crates/yan-eval",
  "crates/yan-runtime",
  "crates/yan-rust-backend",
  "crates/yanc",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"
