[package]
name = "yan-rust-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yan-mir = { path = "../yan-mir" }
yan-runtime = { path = "../yan-runtime" }

[dev-dependencies]
yan-hir = { path = "../yan-hir" }
yan-syntax = { path = "../yan-syntax" }
yan-typeck = { path = "../yan-typeck" }

[lints]
workspace = true
