[package]
name = "yanc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yan-eval = { path = "../yan-eval" }
yan-hir = { path = "../yan-hir" }
yan-source = { path = "../yan-source" }
yan-syntax = { path = "../yan-syntax" }
yan-typeck = { path = "../yan-typeck" }

[lints]
workspace = true
